MarkShop/Controllers/ThongKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarkShop.Controllers
{
    public class ThongKeController : Controller
    {
        QLBanQuanAoDataContext db = new QLBanQuanAoDataContext();
        // GET: ThongKe
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SanPhamTon()
        {
            List<SanPham> listsp = (from s in db.SanPhams where (s.SoLuongTon > 0) select s).ToList();
            return View(listsp);
        }

        public ActionResult DoanhThuThangNam(string NgayBD, string NgayKT)
        {
            List<LoaiSanPham> listlsp = (from s in db.LoaiSanPhams   select s).ToList();
            DateTime bd = Convert.ToDateTime(NgayBD);
            DateTime kt = Convert.ToDateTime(NgayKT);
            //NgayBD = "01/06/2022";
            //NgayKT = "30/06/2022";
            if (NgayBD == null && NgayKT == null)
            {
                NgayBD = "01/01/2022";
                NgayKT = "31/12/2022";
            }
            decimal TongDoanhThu = 0;
            decimal TDTNam = 0;
            decimal TDTNu = 0;
            decimal TDTTat = 0;
            int SoLuong = 0;
            int SoLuongDonGiayNam = 0;
            int SoLuongDonGiayNu = 0;
            int SoLuongDonTat = 0;
            if (!string.IsNullOrEmpty(NgayBD) && !string.IsNullOrEmpty(NgayKT))
            {
                List<HoaDon> listhd = (from s in db.HoaDons where (s.NgayDat >= bd && s.NgayDat <= kt) select s).ToList();
                foreach (var item in listhd)
                {
                    foreach (var items in item.ChiTietHoaDons)
                    {
                        if (items.SanPham.MaLoaiSP == 1)
                        {
                            SoLuongDonGiayNam += 1;
                            TDTNam += (decimal)(items.SoLuong * items.DonGia);
                        }
                        else if (items.SanPham.MaLoaiSP == 2)
                        {
                            SoLuongDonGiayNu += 1;
                            TDTNu += (decimal)(items.SoLuong * items.DonGia);
                        }
                        else
                        {
                            SoLuongDonTat += 1;
                            TDTTat += (decimal)(items.SoLuong * items.DonGia);
                        }
                        SoLuong += (int)items.SoLuong;
                        TongDoanhThu += (decimal)(items.SoLuong * items.DonGia);
                    }
                }
                ViewBag.SLDGiayNam = SoLuongDonGiayNam;
                ViewBag.SLDGiayNu = SoLuongDonGiayNu;
                ViewBag.SLDTat = SoLuongDonTat;
                ViewBag.TongDoanhThu = TongDoanhThu;
                ViewBag.TDTNam = TDTNam;
                ViewBag.TDTNu = TDTNu;
                ViewBag.TDTTat = TDTTat;
                ViewBag.SoLuong = SoLuong;
                return View(listlsp);
            }
            return View();
        }
        private decimal ThongKeTongDoanhThu()
        {
            decimal TongDoanhThu = db.ChiTietHoaDons.Sum(n => n.SoLuong * n.DonGia).Value;
            return TongDoanhThu;
        }
        private double ThongKeDonHang()
        {
            double slhd = db.HoaDons.Count();
            return slhd;
        }
        private double ThongKeKhachHang()
        {
            double slkh = db.KhachHangs.Count();
            return slkh;
        }
        private decimal ThongKeDoanhThuThang(int thang, int nam)
        {
            var lstHD = db.HoaDons.Where(n => n.NgayDat.Value.Month == thang && n.NgayDat.Value.Year == nam);
            decimal TongTien = 0;
            foreach (var item in lstHD)
            {
                TongTien = decimal.Parse(item.ChiTietHoaDons.Sum(n => n.SoLuong * n.DonGia).Value.ToString());
            }
            return TongTien;
        }
        private int TongSL()
        {
            int TongSL = 0;
            var check = db.ChiTietHoaDons.Count();
            if (check == 0)
            {
                return TongSL;
            }
            var cthh = db.ChiTietHoaDons.ToList();
            foreach (var item in cthh)
            {
                TongSL += (int)(item.SoLuong);
            }
            return TongSL;
        }
        private decimal tongnhaphang()
        {
            decimal tongdoanhthu = 0;
            var check = db.ChiTietHoaDons.Count();
            if (check == 0)
            {
                return tongdoanhthu;
            }
            var sp = db.ChiTietHoaDons.ToList();
            foreach (var item in sp)
            {        
                tongdoanhthu += (decimal)(item.SanPham.GiaNhap);            
            }
            return tongdoanhthu;
        }


        //private decimal TongNhapHangS()
        //{
        //    decimal TongDoanhThu = 0;
        //    var check = db.SanPhams.Count();
        //    if (check == 0)
        //    {
        //        return TongDoanhThu;
        //    }
        //    var cthh = db.ChiTietHoaDons.ToList();
        //    var sp = db.SanPhams.ToList();
        //    foreach (var item in sp)
        //    {
        //        foreach (var itemS in cthh)
        //        {
        //            TongDoanhThu = ((decimal)(item.GiaBan)*(int)(itemS.SoLuong) - (decimal)(item.GiaNhap) * (int)(itemS.SoLuong));
        //        }
        //    }
        //    return TongDoanhThu;
        //}


        public ActionResult LoiNhuan()
        {
            ViewBag.SoNgTruyCap = HttpContext.Application["SoNgTruyCap"].ToString();
            ViewBag.SoNgDangTruyCap = HttpContext.Application["SoNgDangTruyCap"].ToString();
            ViewBag.TongDoanhThu = ThongKeTongDoanhThu();
            ViewBag.SLDH = ThongKeDonHang();
            ViewBag.SLKH = ThongKeKhachHang();
            ViewBag.TongSL = TongSL();
            ViewBag.TongDoanhThu = ThongKeTongDoanhThu();
            ViewBag.TongNhapHang = tongnhaphang();
            
            return View();
        }
    }
}

MarkShop/Views/ThongKe/DoanhThuThangNam.cshtml
@model IEnumerable<MarkShop.LoaiSanPham>
@{
    ViewBag.Title = "DoanhThuThangNam";
    Layout = "~/Views/Admin/LayoutAdmin.cshtml";
}
<style>
    a {
        width: 50%;
        display: inline-block;
    }
</style>
<h3 class="text-center lead mb-3 font-weight-bold" style="font-size: 36px; text-shadow: 0 0 8px rgba(0,0,0,0.2)" data-aos="flip-right">
    Doanh thu theo khoảng
</h3>
@using (Html.BeginForm("DoanhThuThangNam", "ThongKe"))
{
    <div class="d-flex">
        <div style="margin-right:10px">
            <a>Từ</a>
            <input type="date" name="NgayBD" id="ngayBD" class="mb-2" style="color:black" />
        </div>
        <div>
            <a>đến</a>
            <input type="date" name="NgayKT" id="ngayKT" class="mb-2" style="color:black" />
        </div>
        <button class="btnStyle btn1 ml-3" style="width: 90px; height: 40px; line-height:16px; margin-top:35px" id="btnTim">Tìm</button>
    </div>
}
<table class="table table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Số lượng đã bán</th>
            <th>Tổng doanh thu</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@ViewBag.SoLuong</td>
            <td>@ViewBag.TongDoanhThu</td>
        </tr>
    </tbody>
</table>

<script>
    document.getElementById("btnTim").onclick = function (e) {
        var selectedStartDate = document.getElementById("ngayBD").value;
        var selectedEndDate = document.getElementById("ngayKT").value;
        if (!Date.parse(selectedStartDate) && !Date.parse(selectedEndDate)) {
            Swal.fire({
                title: 'Thông báo',
                text: 'Vui lòng chọn ngày bắt đầu và kết thúc!',
                icon: 'error',
            })
            e.preventDefault();
        }
        if (Date.parse(selectedStartDate) > Date.parse(selectedEndDate)) {
            Swal.fire({
                title: 'Thông báo',
                text: 'Ngày kết thúc hàng phải lớn hơn ngày bắt đầu!',
                icon: 'error',
            })
            e.preventDefault();
        }
        if (!Date.parse(selectedStartDate) || !Date.parse(selectedEndDate)) {
            Swal.fire({
                title: 'Thông báo',
                text: 'Vui long nhap ngay bat dau va ket thuc',
                icon: 'error',
            })
            e.preventDefault();
        }
    }
</script>

MarkShop/Views/ThongKe/LoiNhuan.cshtml
@{
    ViewBag.Title = "LoiNhuan";
    Layout = "~/Views/Admin/LayoutAdmin.cshtml";
}
<div class="list-of-members d-flex">
    <div class="TongDT" style="background-color:aqua; width:200px; height:100px; text-align:center;">
        <div>

        </div>
        <div>
            <h3 style="margin-top:20px;">@String.Format("{0:0,0}", ViewBag.TongDoanhThu)</h3>
            <p>Doanh Thu</p>
        </div>
    </div>
    <div class="SLUser" style="margin-left: 20px; background-color: grey; width: 200px; height: 100px; text-align: center;">
        <div>

        </div>
        <div>
            <h3 style="margin-top:20px">@ViewBag.SLKH</h3>
            <p>Khách hàng</p>
        </div>
    </div>
    <div class="SLDH" style="margin-left: 20px; background-color: sandybrown; width: 200px; height: 100px; text-align: center;">
        <div>

        </div>
        <div>
            <h3 style="margin-top:20px">@ViewBag.SLDH</h3>
            <p>Hóa đơn</p>
        </div>
    </div>
    <div class="SLDaTruyCap" style="margin-left: 20px; background-color: orangered; width: 200px; height: 100px; text-align: center; ">
        <div>

        </div>
        <div>
            <h3 style="margin-top:20px">@ViewBag.SoNgTruycap</h3>
            <p>Người đã truy cập</p>
        </div>
    </div>
    <div class="SLDangTruyCap" style="margin-left: 20px; background-color: limegreen; width: 200px; height: 100px; text-align: center;">
        <div>

        </div>
        <div>
            <h3 style="margin-top:20px">@ViewBag.SoNgDangTruyCap</h3>
            <p>Người đang truy cập</p>
        </div>
    </div>
</div>
<h3 class="text-center lead mb-3 font-weight-bold" style="font-size: 36px; text-shadow: 0 0 8px rgba(0,0,0,0.2)" data-aos="flip-right">
    Lợi nhuận
</h3>
<table class="table table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Số lượng đã bán</th>
            <th>Tổng tiền doanh thu</th>
            <th>Tổng tiền nhập hàng</th>
            <th>Lợi Nhuận</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@ViewBag.TongSL</td>
            <td>@String.Format("{0:0,0}", ViewBag.TongDoanhThu)</td>
            <td>@String.Format("{0:0,0}", ViewBag.TongNhapHang)</td>
            <td>@String.Format("{0:0,0}", ViewBag.TongDoanhThu - ViewBag.TongNhapHang)</td>
        </tr>
    </tbody>
</table>

MarkShop/Views/ThongKe/SanPhamTon.cshtml
@model IEnumerable<MarkShop.SanPham>
@{
    ViewBag.Title = "SanPhamTon";
    Layout = "~/Views/Admin/LayoutAdmin.cshtml";
}

<h3 class="text-center lead mb-3 font-weight-bold" style="font-size: 36px; text-shadow: 0 0 8px rgba(0,0,0,0.2)" data-aos="flip-right">
    Danh mục các sản phẩm tồn
</h3>
<br />
<br />
@using (Html.BeginForm("timKiemSanPham", "ThemXoaSua"))
{
    <div class="d-flex" data-aos="fade-left">
        <div class="group">
            <input class="txtTimKiem" type="text" name="tenSP" autocomplete="off" required>
            <label class="timKiem">Tìm kiếm sản phẩm</label>
        </div>
        <button class="btnStyle btn1 ml-3" style="width:90px; height:40px; line-height:16px;">Tìm</button>
    </div>
}
<table class="table table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Mã sản phẩm</th>
            <th style="width: 300px;">Tên sản phẩm</th>
            <th>Hình ảnh</th>
            <th>Số lượng tồn</th>
            <th>Đơn giá</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.MaSP</td>
                <td>@item.TenSP</td>
                <td style="width: 120px">
                    <a href="~/Images/@item.Anh" data-lightbox="listImg">
                        <img src="~/Images/@item.Anh" height="70" />
                    </a>
                </td>
                <td>
                    @item.SoLuongTon
                </td>
                <td>
                    @String.Format("{0:0,0}", item.GiaBan)
                </td>
            </tr>
        }
    </tbody>
</table>